In [1]:
from slomo_train import *
import os
from tensorflow.python.client import device_lib
import tensorflow as tf

In [2]:
os.environ['CUDA_DEVICE_ORDER'] = "PCI_BUS_ID"
os.environ['CUDA_VISIBLE_DEVICES'] = "1"
print(device_lib.list_local_devices())

# config = tf.ConfigProto(device_count={'GPU': 2}, log_device_placement=True)
config = tf.ConfigProto(log_device_placement=True)

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 38397747569630729
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 7734149120
locality {
  bus_id: 1
  links {
  }
}
incarnation: 393593534192518465
physical_device_desc: "device: 0, name: GeForce GTX 1080, pci bus id: 0000:02:00.0, compute capability: 6.1"
]


In [3]:
with tf.device('/gpu:0'):
    a = tf.constant(np.ones([500, 5000]))
    b = tf.constant(np.ones([5000, 1000]))
    c = tf.matmul(a, b)
with tf.Session(config=config) as sess:
#     for __ in range(1000):
    print(sess.run(c))

[[5000. 5000. 5000. ... 5000. 5000. 5000.]
 [5000. 5000. 5000. ... 5000. 5000. 5000.]
 [5000. 5000. 5000. ... 5000. 5000. 5000.]
 ...
 [5000. 5000. 5000. ... 5000. 5000. 5000.]
 [5000. 5000. 5000. ... 5000. 5000. 5000.]
 [5000. 5000. 5000. ... 5000. 5000. 5000.]]


In [ ]:
# !python slomo_train.py --subset=train